//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilanaZhiganshina320_SR.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int Id_foto { get; set; }
        public byte[] Foto { get; set; }
        public string Opisanie_foto { get; set; }
        public Nullable<int> Id_pet { get; set; }
    
        public virtual Pet Pet { get; set; }
    }
}
